version: "3"
services:
  web:
    container_name: "database-frontend"
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/database-frontend
      - ./database-frontend/node_modules
